name: ci

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"
      - uses: golangci/golangci-lint-action@v6
        with:
          version: latest

  test:
    name: test / go-${{ matrix.go-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.23.2"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test ./...
      - run: go test -race ./...
      - run: go vet ./...
      - run: bash ./scripts/check-dependencies.sh
